const mongoose = require('mongoose');
const { Schema } = mongoose;

const taskSchema = new Schema({
  // _id is automatically generated by MongoDB as an ObjectId, 
  // so you don't need to explicitly define it here.

  title: {
    type: String,
    required: true,
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  assignedTo: [{
    type: Schema.Types.ObjectId,
    ref: 'Employee' // This creates a relationship to your User collection
  }],
  criticality: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    enum: ['open', 'done'],
    default: 'open'
  },
  startedAt: {
    type: Date,
    default: null
  },
  completedAt: {
    type: Date,
    default: null
  },

  sector: [{
    type: String,
    trim: true
  }],

  // --- FOR AI LEARNING ---
  resolutionSummary: {
    type: String,
    trim: true
  },
  rootCause: {
    type: String,
    trim: true
  }
}, {

  timestamps: true 
});

// Compile the schema into a model
const Task = mongoose.model('Task', taskSchema);

module.exports = Task;